//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using GSF.ASN1;
using GSF.ASN1.Attributes;
using GSF.ASN1.Attributes.Constraints;
using GSF.ASN1.Coders;
using GSF.ASN1.Types;

namespace GSF.MMS.Model
{
    
    [ASN1PreparedElement]
    [ASN1BoxedType(Name = "AdditionalSupportOptions")]
    public class AdditionalSupportOptions : IASN1PreparedElement
    {
        private static readonly IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(AdditionalSupportOptions));
        private BitString val;

        public AdditionalSupportOptions()
        {
        }

        public AdditionalSupportOptions(BitString value)
        {
            Value = value;
        }

        [ASN1BitString(Name = "AdditionalSupportOptions")]
        [ASN1SizeConstraint(Max = 23L)]
        public BitString Value
        {
            get
            {
                return val;
            }
            set
            {
                val = value;
            }
        }


        public void initWithDefaults()
        {
        }

        public IASN1PreparedElementData PreparedData
        {
            get
            {
                return preparedData;
            }
        }
    }
}