//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using GSF.ASN1;
using GSF.ASN1.Attributes;
using GSF.ASN1.Coders;

namespace GSF.MMS.Model
{
    
    [ASN1PreparedElement]
    [ASN1Sequence(Name = "AlterEventConditionMonitoring_Request", IsSet = false)]
    public class AlterEventConditionMonitoring_Request : IASN1PreparedElement
    {
        private static readonly IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(AlterEventConditionMonitoring_Request));
        private bool alarmSummaryReports_;

        private bool alarmSummaryReports_present;
        private bool enabled_;

        private bool enabled_present;
        private Unsigned32 evaluationInterval_;

        private bool evaluationInterval_present;
        private ObjectName eventConditionName_;


        private Priority priority_;

        private bool priority_present;

        [ASN1Element(Name = "eventConditionName", IsOptional = false, HasTag = true, Tag = 0, HasDefaultValue = false)]
        public ObjectName EventConditionName
        {
            get
            {
                return eventConditionName_;
            }
            set
            {
                eventConditionName_ = value;
            }
        }

        [ASN1Boolean(Name = "")]
        [ASN1Element(Name = "enabled", IsOptional = true, HasTag = true, Tag = 1, HasDefaultValue = false)]
        public bool Enabled
        {
            get
            {
                return enabled_;
            }
            set
            {
                enabled_ = value;
                enabled_present = true;
            }
        }

        [ASN1Element(Name = "priority", IsOptional = true, HasTag = true, Tag = 2, HasDefaultValue = false)]
        public Priority Priority
        {
            get
            {
                return priority_;
            }
            set
            {
                priority_ = value;
                priority_present = true;
            }
        }


        [ASN1Boolean(Name = "")]
        [ASN1Element(Name = "alarmSummaryReports", IsOptional = true, HasTag = true, Tag = 3, HasDefaultValue = false)]
        public bool AlarmSummaryReports
        {
            get
            {
                return alarmSummaryReports_;
            }
            set
            {
                alarmSummaryReports_ = value;
                alarmSummaryReports_present = true;
            }
        }


        [ASN1Element(Name = "evaluationInterval", IsOptional = true, HasTag = true, Tag = 4, HasDefaultValue = false)]
        public Unsigned32 EvaluationInterval
        {
            get
            {
                return evaluationInterval_;
            }
            set
            {
                evaluationInterval_ = value;
                evaluationInterval_present = true;
            }
        }

        public void initWithDefaults()
        {
        }

        public IASN1PreparedElementData PreparedData
        {
            get
            {
                return preparedData;
            }
        }


        public bool isEnabledPresent()
        {
            return enabled_present;
        }

        public bool isPriorityPresent()
        {
            return priority_present;
        }

        public bool isAlarmSummaryReportsPresent()
        {
            return alarmSummaryReports_present;
        }

        public bool isEvaluationIntervalPresent()
        {
            return evaluationInterval_present;
        }
    }
}