//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using GSF.ASN1;
using GSF.ASN1.Attributes;
using GSF.ASN1.Coders;

namespace GSF.MMS.Model
{
    
    [ASN1PreparedElement]
    [ASN1Sequence(Name = "DefineNamedType_Request", IsSet = false)]
    public class DefineNamedType_Request : IASN1PreparedElement
    {
        private static readonly IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(DefineNamedType_Request));
        private ObjectName typeName_;


        private TypeSpecification typeSpecification_;

        [ASN1Element(Name = "typeName", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public ObjectName TypeName
        {
            get
            {
                return typeName_;
            }
            set
            {
                typeName_ = value;
            }
        }

        [ASN1Element(Name = "typeSpecification", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public TypeSpecification TypeSpecification
        {
            get
            {
                return typeSpecification_;
            }
            set
            {
                typeSpecification_ = value;
            }
        }


        public void initWithDefaults()
        {
        }


        public IASN1PreparedElementData PreparedData
        {
            get
            {
                return preparedData;
            }
        }
    }
}