//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using GSF.ASN1;
using GSF.ASN1.Attributes;
using GSF.ASN1.Coders;
using GSF.ASN1.Types;

namespace GSF.MMS.Model
{
    
    [ASN1PreparedElement]
    [ASN1Choice(Name = "EventTime")]
    public class EventTime : IASN1PreparedElement
    {
        private static readonly IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(EventTime));
        private TimeOfDay timeOfDay_;
        private bool timeOfDay_selected;


        private Unsigned32 timeSequenceIdentifier_;
        private bool timeSequenceIdentifier_selected;


        private NullObject undefined_;
        private bool undefined_selected;

        [ASN1Element(Name = "timeOfDay", IsOptional = false, HasTag = true, Tag = 0, HasDefaultValue = false)]
        public TimeOfDay TimeOfDay
        {
            get
            {
                return timeOfDay_;
            }
            set
            {
                selectTimeOfDay(value);
            }
        }

        [ASN1Element(Name = "timeSequenceIdentifier", IsOptional = false, HasTag = true, Tag = 1, HasDefaultValue = false)]
        public Unsigned32 TimeSequenceIdentifier
        {
            get
            {
                return timeSequenceIdentifier_;
            }
            set
            {
                selectTimeSequenceIdentifier(value);
            }
        }


        [ASN1Null(Name = "undefined")]
        [ASN1Element(Name = "undefined", IsOptional = false, HasTag = true, Tag = 2, HasDefaultValue = false)]
        public NullObject Undefined
        {
            get
            {
                return undefined_;
            }
            set
            {
                selectUndefined(value);
            }
        }

        public void initWithDefaults()
        {
        }

        public IASN1PreparedElementData PreparedData
        {
            get
            {
                return preparedData;
            }
        }


        public bool isTimeOfDaySelected()
        {
            return timeOfDay_selected;
        }


        public void selectTimeOfDay(TimeOfDay val)
        {
            timeOfDay_ = val;
            timeOfDay_selected = true;


            timeSequenceIdentifier_selected = false;

            undefined_selected = false;
        }


        public bool isTimeSequenceIdentifierSelected()
        {
            return timeSequenceIdentifier_selected;
        }


        public void selectTimeSequenceIdentifier(Unsigned32 val)
        {
            timeSequenceIdentifier_ = val;
            timeSequenceIdentifier_selected = true;


            timeOfDay_selected = false;

            undefined_selected = false;
        }


        public bool isUndefinedSelected()
        {
            return undefined_selected;
        }


        public void selectUndefined()
        {
            selectUndefined(new NullObject());
        }


        public void selectUndefined(NullObject val)
        {
            undefined_ = val;
            undefined_selected = true;


            timeOfDay_selected = false;

            timeSequenceIdentifier_selected = false;
        }
    }
}