//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System.Collections.Generic;
using GSF.ASN1;
using GSF.ASN1.Attributes;
using GSF.ASN1.Coders;

namespace GSF.MMS.Model
{
    
    [ASN1PreparedElement]
    [ASN1Sequence(Name = "ExchangeData_Response", IsSet = false)]
    public class ExchangeData_Response : IASN1PreparedElement
    {
        private static readonly IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(ExchangeData_Response));
        private ICollection<Data> listOfResponseData_;

        [ASN1SequenceOf(Name = "listOfResponseData", IsSetOf = false)]
        [ASN1Element(Name = "listOfResponseData", IsOptional = false, HasTag = true, Tag = 0, HasDefaultValue = false)]
        public ICollection<Data> ListOfResponseData
        {
            get
            {
                return listOfResponseData_;
            }
            set
            {
                listOfResponseData_ = value;
            }
        }


        public void initWithDefaults()
        {
        }


        public IASN1PreparedElementData PreparedData
        {
            get
            {
                return preparedData;
            }
        }
    }
}