//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using GSF.ASN1;
using GSF.ASN1.Attributes;
using GSF.ASN1.Coders;

namespace GSF.MMS.Model
{
    
    [ASN1PreparedElement]
    [ASN1Choice(Name = "GetVariableAccessAttributes_Request")]
    public class GetVariableAccessAttributes_Request : IASN1PreparedElement
    {
        private static readonly IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(GetVariableAccessAttributes_Request));
        private Address address_;
        private bool address_selected;
        private ObjectName name_;
        private bool name_selected;


        [ASN1Element(Name = "name", IsOptional = false, HasTag = true, Tag = 0, HasDefaultValue = false)]
        public ObjectName Name
        {
            get
            {
                return name_;
            }
            set
            {
                selectName(value);
            }
        }


        [ASN1Element(Name = "address", IsOptional = false, HasTag = true, Tag = 1, HasDefaultValue = false)]
        public Address Address
        {
            get
            {
                return address_;
            }
            set
            {
                selectAddress(value);
            }
        }

        public void initWithDefaults()
        {
        }

        public IASN1PreparedElementData PreparedData
        {
            get
            {
                return preparedData;
            }
        }


        public bool isNameSelected()
        {
            return name_selected;
        }


        public void selectName(ObjectName val)
        {
            name_ = val;
            name_selected = true;


            address_selected = false;
        }


        public bool isAddressSelected()
        {
            return address_selected;
        }


        public void selectAddress(Address val)
        {
            address_ = val;
            address_selected = true;


            name_selected = false;
        }
    }
}