//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System.Collections.Generic;
using GSF.ASN1;
using GSF.ASN1.Attributes;
using GSF.ASN1.Coders;

namespace GSF.MMS.Model
{
    
    [ASN1PreparedElement]
    [ASN1Sequence(Name = "InitiateUploadSequence_Response", IsSet = false)]
    public class InitiateUploadSequence_Response : IASN1PreparedElement
    {
        private static readonly IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(InitiateUploadSequence_Response));
        private ICollection<MMSString> listOfCapabilities_;
        private Integer32 ulsmID_;

        [ASN1Element(Name = "ulsmID", IsOptional = false, HasTag = true, Tag = 0, HasDefaultValue = false)]
        public Integer32 UlsmID
        {
            get
            {
                return ulsmID_;
            }
            set
            {
                ulsmID_ = value;
            }
        }


        [ASN1SequenceOf(Name = "listOfCapabilities", IsSetOf = false)]
        [ASN1Element(Name = "listOfCapabilities", IsOptional = false, HasTag = true, Tag = 1, HasDefaultValue = false)]
        public ICollection<MMSString> ListOfCapabilities
        {
            get
            {
                return listOfCapabilities_;
            }
            set
            {
                listOfCapabilities_ = value;
            }
        }


        public void initWithDefaults()
        {
        }


        public IASN1PreparedElementData PreparedData
        {
            get
            {
                return preparedData;
            }
        }
    }
}