//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using GSF.ASN1;
using GSF.ASN1.Attributes;
using GSF.ASN1.Coders;

namespace GSF.MMS.Model
{
    
    [ASN1PreparedElement]
    [ASN1Sequence(Name = "Journal_Variable", IsSet = false)]
    public class Journal_Variable : IASN1PreparedElement
    {
        private static readonly IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(Journal_Variable));
        private Data valueSpecification_;
        private MMS255String variableTag_;

        [ASN1Element(Name = "variableTag", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public MMS255String VariableTag
        {
            get
            {
                return variableTag_;
            }
            set
            {
                variableTag_ = value;
            }
        }


        [ASN1Element(Name = "valueSpecification", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public Data ValueSpecification
        {
            get
            {
                return valueSpecification_;
            }
            set
            {
                valueSpecification_ = value;
            }
        }


        public void initWithDefaults()
        {
        }


        public IASN1PreparedElementData PreparedData
        {
            get
            {
                return preparedData;
            }
        }
    }
}