//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using GSF.ASN1;
using GSF.ASN1.Attributes;
using GSF.ASN1.Coders;

namespace GSF.MMS.Model
{
    
    [ASN1PreparedElement]
    [ASN1Choice(Name = "LoadData")]
    public class LoadData : IASN1PreparedElement
    {
        private static readonly IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(LoadData));
        private byte[] non_coded_;
        private bool non_coded_selected;


        [ASN1OctetString(Name = "")]
        [ASN1Element(Name = "non-coded", IsOptional = false, HasTag = true, Tag = 0, HasDefaultValue = false)]
        public byte[] Non_coded
        {
            get
            {
                return non_coded_;
            }
            set
            {
                selectNon_coded(value);
            }
        }


        public void initWithDefaults()
        {
        }

        public IASN1PreparedElementData PreparedData
        {
            get
            {
                return preparedData;
            }
        }

        public bool isNon_codedSelected()
        {
            return non_coded_selected;
        }


        public void selectNon_coded(byte[] val)
        {
            non_coded_ = val;
            non_coded_selected = true;


            non_coded_selected = false;
        }
    }
}