//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using GSF.ASN1;
using GSF.ASN1.Attributes;
using GSF.ASN1.Coders;

namespace GSF.MMS.Model
{
    
    [ASN1PreparedElement]
    [ASN1Sequence(Name = "OperatorCommunicationParameters", IsSet = false)]
    public class OperatorCommunicationParameters : IASN1PreparedElement
    {
        private static readonly IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(OperatorCommunicationParameters));
        private long input_time_out_;

        [ASN1Integer(Name = "")]
        [ASN1Element(Name = "input-time-out", IsOptional = false, HasTag = true, Tag = 0, HasDefaultValue = false)]
        public long Input_time_out
        {
            get
            {
                return input_time_out_;
            }
            set
            {
                input_time_out_ = value;
            }
        }


        public void initWithDefaults()
        {
        }


        public IASN1PreparedElementData PreparedData
        {
            get
            {
                return preparedData;
            }
        }
    }
}