//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using GSF.ASN1;
using GSF.ASN1.Attributes;
using GSF.ASN1.Coders;

namespace GSF.MMS.Model
{
    
    [ASN1PreparedElement]
    [ASN1Sequence(Name = "RejectPDU", IsSet = false)]
    public class RejectPDU : IASN1PreparedElement
    {
        private static readonly IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(RejectPDU));
        private Unsigned32 originalInvokeID_;

        private bool originalInvokeID_present;


        private RejectReasonChoiceType rejectReason_;

        [ASN1Element(Name = "originalInvokeID", IsOptional = true, HasTag = true, Tag = 0, HasDefaultValue = false)]
        public Unsigned32 OriginalInvokeID
        {
            get
            {
                return originalInvokeID_;
            }
            set
            {
                originalInvokeID_ = value;
                originalInvokeID_present = true;
            }
        }


        [ASN1Element(Name = "rejectReason", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public RejectReasonChoiceType RejectReason
        {
            get
            {
                return rejectReason_;
            }
            set
            {
                rejectReason_ = value;
            }
        }


        public void initWithDefaults()
        {
        }


        public IASN1PreparedElementData PreparedData
        {
            get
            {
                return preparedData;
            }
        }

        public bool isOriginalInvokeIDPresent()
        {
            return originalInvokeID_present;
        }

        [ASN1PreparedElement]
        [ASN1Choice(Name = "rejectReason")]
        public class RejectReasonChoiceType : IASN1PreparedElement
        {
            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(RejectReasonChoiceType));
            private long cancel_errorPDU_;
            private bool cancel_errorPDU_selected;
            private long cancel_requestPDU_;
            private bool cancel_requestPDU_selected;
            private long cancel_responsePDU_;
            private bool cancel_responsePDU_selected;
            private long conclude_errorPDU_;
            private bool conclude_errorPDU_selected;
            private long conclude_requestPDU_;
            private bool conclude_requestPDU_selected;
            private long conclude_responsePDU_;
            private bool conclude_responsePDU_selected;
            private long confirmed_errorPDU_;
            private bool confirmed_errorPDU_selected;
            private long confirmed_requestPDU_;
            private bool confirmed_requestPDU_selected;


            private long confirmed_responsePDU_;
            private bool confirmed_responsePDU_selected;
            private long pdu_error_;
            private bool pdu_error_selected;


            private long unconfirmedPDU_;
            private bool unconfirmedPDU_selected;

            [ASN1Integer(Name = "")]
            [ASN1Element(Name = "confirmed-requestPDU", IsOptional = false, HasTag = true, Tag = 1, HasDefaultValue = false)]
            public long Confirmed_requestPDU
            {
                get
                {
                    return confirmed_requestPDU_;
                }
                set
                {
                    selectConfirmed_requestPDU(value);
                }
            }

            [ASN1Integer(Name = "")]
            [ASN1Element(Name = "confirmed-responsePDU", IsOptional = false, HasTag = true, Tag = 2, HasDefaultValue = false)]
            public long Confirmed_responsePDU
            {
                get
                {
                    return confirmed_responsePDU_;
                }
                set
                {
                    selectConfirmed_responsePDU(value);
                }
            }

            [ASN1Integer(Name = "")]
            [ASN1Element(Name = "confirmed-errorPDU", IsOptional = false, HasTag = true, Tag = 3, HasDefaultValue = false)]
            public long Confirmed_errorPDU
            {
                get
                {
                    return confirmed_errorPDU_;
                }
                set
                {
                    selectConfirmed_errorPDU(value);
                }
            }


            [ASN1Integer(Name = "")]
            [ASN1Element(Name = "unconfirmedPDU", IsOptional = false, HasTag = true, Tag = 4, HasDefaultValue = false)]
            public long UnconfirmedPDU
            {
                get
                {
                    return unconfirmedPDU_;
                }
                set
                {
                    selectUnconfirmedPDU(value);
                }
            }


            [ASN1Integer(Name = "")]
            [ASN1Element(Name = "pdu-error", IsOptional = false, HasTag = true, Tag = 5, HasDefaultValue = false)]
            public long Pdu_error
            {
                get
                {
                    return pdu_error_;
                }
                set
                {
                    selectPdu_error(value);
                }
            }


            [ASN1Integer(Name = "")]
            [ASN1Element(Name = "cancel-requestPDU", IsOptional = false, HasTag = true, Tag = 6, HasDefaultValue = false)]
            public long Cancel_requestPDU
            {
                get
                {
                    return cancel_requestPDU_;
                }
                set
                {
                    selectCancel_requestPDU(value);
                }
            }


            [ASN1Integer(Name = "")]
            [ASN1Element(Name = "cancel-responsePDU", IsOptional = false, HasTag = true, Tag = 7, HasDefaultValue = false)]
            public long Cancel_responsePDU
            {
                get
                {
                    return cancel_responsePDU_;
                }
                set
                {
                    selectCancel_responsePDU(value);
                }
            }


            [ASN1Integer(Name = "")]
            [ASN1Element(Name = "cancel-errorPDU", IsOptional = false, HasTag = true, Tag = 8, HasDefaultValue = false)]
            public long Cancel_errorPDU
            {
                get
                {
                    return cancel_errorPDU_;
                }
                set
                {
                    selectCancel_errorPDU(value);
                }
            }


            [ASN1Integer(Name = "")]
            [ASN1Element(Name = "conclude-requestPDU", IsOptional = false, HasTag = true, Tag = 9, HasDefaultValue = false)]
            public long Conclude_requestPDU
            {
                get
                {
                    return conclude_requestPDU_;
                }
                set
                {
                    selectConclude_requestPDU(value);
                }
            }


            [ASN1Integer(Name = "")]
            [ASN1Element(Name = "conclude-responsePDU", IsOptional = false, HasTag = true, Tag = 10, HasDefaultValue = false)]
            public long Conclude_responsePDU
            {
                get
                {
                    return conclude_responsePDU_;
                }
                set
                {
                    selectConclude_responsePDU(value);
                }
            }


            [ASN1Integer(Name = "")]
            [ASN1Element(Name = "conclude-errorPDU", IsOptional = false, HasTag = true, Tag = 11, HasDefaultValue = false)]
            public long Conclude_errorPDU
            {
                get
                {
                    return conclude_errorPDU_;
                }
                set
                {
                    selectConclude_errorPDU(value);
                }
            }

            public void initWithDefaults()
            {
            }

            public IASN1PreparedElementData PreparedData
            {
                get
                {
                    return preparedData;
                }
            }


            public bool isConfirmed_requestPDUSelected()
            {
                return confirmed_requestPDU_selected;
            }


            public void selectConfirmed_requestPDU(long val)
            {
                confirmed_requestPDU_ = val;
                confirmed_requestPDU_selected = true;


                confirmed_requestPDU_selected = false;

                confirmed_responsePDU_selected = false;

                confirmed_errorPDU_selected = false;

                unconfirmedPDU_selected = false;

                pdu_error_selected = false;

                cancel_requestPDU_selected = false;

                cancel_responsePDU_selected = false;

                cancel_errorPDU_selected = false;

                conclude_requestPDU_selected = false;

                conclude_responsePDU_selected = false;

                conclude_errorPDU_selected = false;
            }


            public bool isConfirmed_responsePDUSelected()
            {
                return confirmed_responsePDU_selected;
            }


            public void selectConfirmed_responsePDU(long val)
            {
                confirmed_responsePDU_ = val;
                confirmed_responsePDU_selected = true;


                confirmed_requestPDU_selected = false;

                confirmed_responsePDU_selected = false;

                confirmed_errorPDU_selected = false;

                unconfirmedPDU_selected = false;

                pdu_error_selected = false;

                cancel_requestPDU_selected = false;

                cancel_responsePDU_selected = false;

                cancel_errorPDU_selected = false;

                conclude_requestPDU_selected = false;

                conclude_responsePDU_selected = false;

                conclude_errorPDU_selected = false;
            }


            public bool isConfirmed_errorPDUSelected()
            {
                return confirmed_errorPDU_selected;
            }


            public void selectConfirmed_errorPDU(long val)
            {
                confirmed_errorPDU_ = val;
                confirmed_errorPDU_selected = true;


                confirmed_requestPDU_selected = false;

                confirmed_responsePDU_selected = false;

                confirmed_errorPDU_selected = false;

                unconfirmedPDU_selected = false;

                pdu_error_selected = false;

                cancel_requestPDU_selected = false;

                cancel_responsePDU_selected = false;

                cancel_errorPDU_selected = false;

                conclude_requestPDU_selected = false;

                conclude_responsePDU_selected = false;

                conclude_errorPDU_selected = false;
            }


            public bool isUnconfirmedPDUSelected()
            {
                return unconfirmedPDU_selected;
            }


            public void selectUnconfirmedPDU(long val)
            {
                unconfirmedPDU_ = val;
                unconfirmedPDU_selected = true;


                confirmed_requestPDU_selected = false;

                confirmed_responsePDU_selected = false;

                confirmed_errorPDU_selected = false;

                pdu_error_selected = false;

                cancel_requestPDU_selected = false;

                cancel_responsePDU_selected = false;

                cancel_errorPDU_selected = false;

                conclude_requestPDU_selected = false;

                conclude_responsePDU_selected = false;

                conclude_errorPDU_selected = false;
            }


            public bool isPdu_errorSelected()
            {
                return pdu_error_selected;
            }


            public void selectPdu_error(long val)
            {
                pdu_error_ = val;
                pdu_error_selected = true;


                confirmed_requestPDU_selected = false;

                confirmed_responsePDU_selected = false;

                confirmed_errorPDU_selected = false;

                unconfirmedPDU_selected = false;

                pdu_error_selected = false;

                cancel_requestPDU_selected = false;

                cancel_responsePDU_selected = false;

                cancel_errorPDU_selected = false;

                conclude_requestPDU_selected = false;

                conclude_responsePDU_selected = false;

                conclude_errorPDU_selected = false;
            }


            public bool isCancel_requestPDUSelected()
            {
                return cancel_requestPDU_selected;
            }


            public void selectCancel_requestPDU(long val)
            {
                cancel_requestPDU_ = val;
                cancel_requestPDU_selected = true;


                confirmed_requestPDU_selected = false;

                confirmed_responsePDU_selected = false;

                confirmed_errorPDU_selected = false;

                unconfirmedPDU_selected = false;

                pdu_error_selected = false;

                cancel_requestPDU_selected = false;

                cancel_responsePDU_selected = false;

                cancel_errorPDU_selected = false;

                conclude_requestPDU_selected = false;

                conclude_responsePDU_selected = false;

                conclude_errorPDU_selected = false;
            }


            public bool isCancel_responsePDUSelected()
            {
                return cancel_responsePDU_selected;
            }


            public void selectCancel_responsePDU(long val)
            {
                cancel_responsePDU_ = val;
                cancel_responsePDU_selected = true;


                confirmed_requestPDU_selected = false;

                confirmed_responsePDU_selected = false;

                confirmed_errorPDU_selected = false;

                unconfirmedPDU_selected = false;

                pdu_error_selected = false;

                cancel_requestPDU_selected = false;

                cancel_responsePDU_selected = false;

                cancel_errorPDU_selected = false;

                conclude_requestPDU_selected = false;

                conclude_responsePDU_selected = false;

                conclude_errorPDU_selected = false;
            }


            public bool isCancel_errorPDUSelected()
            {
                return cancel_errorPDU_selected;
            }


            public void selectCancel_errorPDU(long val)
            {
                cancel_errorPDU_ = val;
                cancel_errorPDU_selected = true;


                confirmed_requestPDU_selected = false;

                confirmed_responsePDU_selected = false;

                confirmed_errorPDU_selected = false;

                unconfirmedPDU_selected = false;

                pdu_error_selected = false;

                cancel_requestPDU_selected = false;

                cancel_responsePDU_selected = false;

                cancel_errorPDU_selected = false;

                conclude_requestPDU_selected = false;

                conclude_responsePDU_selected = false;

                conclude_errorPDU_selected = false;
            }


            public bool isConclude_requestPDUSelected()
            {
                return conclude_requestPDU_selected;
            }


            public void selectConclude_requestPDU(long val)
            {
                conclude_requestPDU_ = val;
                conclude_requestPDU_selected = true;


                confirmed_requestPDU_selected = false;

                confirmed_responsePDU_selected = false;

                confirmed_errorPDU_selected = false;

                unconfirmedPDU_selected = false;

                pdu_error_selected = false;

                cancel_requestPDU_selected = false;

                cancel_responsePDU_selected = false;

                cancel_errorPDU_selected = false;

                conclude_requestPDU_selected = false;

                conclude_responsePDU_selected = false;

                conclude_errorPDU_selected = false;
            }


            public bool isConclude_responsePDUSelected()
            {
                return conclude_responsePDU_selected;
            }


            public void selectConclude_responsePDU(long val)
            {
                conclude_responsePDU_ = val;
                conclude_responsePDU_selected = true;


                confirmed_requestPDU_selected = false;

                confirmed_responsePDU_selected = false;

                confirmed_errorPDU_selected = false;

                unconfirmedPDU_selected = false;

                pdu_error_selected = false;

                cancel_requestPDU_selected = false;

                cancel_responsePDU_selected = false;

                cancel_errorPDU_selected = false;

                conclude_requestPDU_selected = false;

                conclude_responsePDU_selected = false;

                conclude_errorPDU_selected = false;
            }


            public bool isConclude_errorPDUSelected()
            {
                return conclude_errorPDU_selected;
            }


            public void selectConclude_errorPDU(long val)
            {
                conclude_errorPDU_ = val;
                conclude_errorPDU_selected = true;


                confirmed_requestPDU_selected = false;

                confirmed_responsePDU_selected = false;

                confirmed_errorPDU_selected = false;

                unconfirmedPDU_selected = false;

                pdu_error_selected = false;

                cancel_requestPDU_selected = false;

                cancel_responsePDU_selected = false;

                cancel_errorPDU_selected = false;

                conclude_requestPDU_selected = false;

                conclude_responsePDU_selected = false;

                conclude_errorPDU_selected = false;
            }
        }
    }
}