//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using GSF.ASN1;
using GSF.ASN1.Attributes;
using GSF.ASN1.Coders;
using GSF.ASN1.Types;

namespace GSF.MMS.Model
{
    
    [ASN1PreparedElement]
    [ASN1Choice(Name = "Response_Detail")]
    public class Response_Detail : IASN1PreparedElement
    {
        private static readonly IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(Response_Detail));
        private CS_GetEventConditionAttributes_Response getEventConditionAttributes_;
        private bool getEventConditionAttributes_selected;
        private CS_GetProgramInvocationAttributes_Response getProgramInvocationAttributes_;
        private bool getProgramInvocationAttributes_selected;
        private NullObject otherRequests_;
        private bool otherRequests_selected;


        private CS_Status_Response status_;
        private bool status_selected;

        [ASN1Null(Name = "otherRequests")]
        [ASN1Element(Name = "otherRequests", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public NullObject OtherRequests
        {
            get
            {
                return otherRequests_;
            }
            set
            {
                selectOtherRequests(value);
            }
        }


        [ASN1Element(Name = "status", IsOptional = false, HasTag = true, Tag = 0, HasDefaultValue = false)]
        public CS_Status_Response Status
        {
            get
            {
                return status_;
            }
            set
            {
                selectStatus(value);
            }
        }


        [ASN1Element(Name = "getProgramInvocationAttributes", IsOptional = false, HasTag = true, Tag = 45, HasDefaultValue = false)]
        public CS_GetProgramInvocationAttributes_Response GetProgramInvocationAttributes
        {
            get
            {
                return getProgramInvocationAttributes_;
            }
            set
            {
                selectGetProgramInvocationAttributes(value);
            }
        }


        [ASN1Element(Name = "getEventConditionAttributes", IsOptional = false, HasTag = true, Tag = 49, HasDefaultValue = false)]
        public CS_GetEventConditionAttributes_Response GetEventConditionAttributes
        {
            get
            {
                return getEventConditionAttributes_;
            }
            set
            {
                selectGetEventConditionAttributes(value);
            }
        }

        public void initWithDefaults()
        {
        }

        public IASN1PreparedElementData PreparedData
        {
            get
            {
                return preparedData;
            }
        }


        public bool isOtherRequestsSelected()
        {
            return otherRequests_selected;
        }


        public void selectOtherRequests()
        {
            selectOtherRequests(new NullObject());
        }


        public void selectOtherRequests(NullObject val)
        {
            otherRequests_ = val;
            otherRequests_selected = true;


            status_selected = false;

            getProgramInvocationAttributes_selected = false;

            getEventConditionAttributes_selected = false;
        }


        public bool isStatusSelected()
        {
            return status_selected;
        }


        public void selectStatus(CS_Status_Response val)
        {
            status_ = val;
            status_selected = true;


            otherRequests_selected = false;

            getProgramInvocationAttributes_selected = false;

            getEventConditionAttributes_selected = false;
        }


        public bool isGetProgramInvocationAttributesSelected()
        {
            return getProgramInvocationAttributes_selected;
        }


        public void selectGetProgramInvocationAttributes(CS_GetProgramInvocationAttributes_Response val)
        {
            getProgramInvocationAttributes_ = val;
            getProgramInvocationAttributes_selected = true;


            otherRequests_selected = false;

            status_selected = false;

            getEventConditionAttributes_selected = false;
        }


        public bool isGetEventConditionAttributesSelected()
        {
            return getEventConditionAttributes_selected;
        }


        public void selectGetEventConditionAttributes(CS_GetEventConditionAttributes_Response val)
        {
            getEventConditionAttributes_ = val;
            getEventConditionAttributes_selected = true;


            otherRequests_selected = false;

            status_selected = false;

            getProgramInvocationAttributes_selected = false;
        }
    }
}