//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using GSF.ASN1;
using GSF.ASN1.Attributes;
using GSF.ASN1.Coders;

namespace GSF.MMS.Model
{
    
    [ASN1PreparedElement]
    [ASN1Sequence(Name = "SCI_Information", IsSet = false)]
    public class SCI_Information : IASN1PreparedElement
    {
        private static readonly IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(SCI_Information));
        private VMD_File partOne_;


        private Service_and_Parameter_CBBs partTwo_;

        [ASN1Element(Name = "partOne", IsOptional = false, HasTag = true, Tag = 0, HasDefaultValue = false)]
        public VMD_File PartOne
        {
            get
            {
                return partOne_;
            }
            set
            {
                partOne_ = value;
            }
        }

        [ASN1Element(Name = "partTwo", IsOptional = false, HasTag = true, Tag = 1, HasDefaultValue = false)]
        public Service_and_Parameter_CBBs PartTwo
        {
            get
            {
                return partTwo_;
            }
            set
            {
                partTwo_ = value;
            }
        }


        public void initWithDefaults()
        {
        }


        public IASN1PreparedElementData PreparedData
        {
            get
            {
                return preparedData;
            }
        }
    }
}